(() => {
  const CHAVE_DIARIO = 'paisDeGatos.diario';
  const LIMITE_OBSERVACAO = 1000;
  const categorias = ['Rotina', 'Saúde', 'Alimentação', 'Comportamento', 'Medicação', 'Veterinário', 'Momento especial'];
  const humores = ['Tranquilo', 'Carinhoso', 'Brincalhão', 'Curioso', 'Assustado', 'Irritado', 'Mais quieto que o normal'];
  const energias = ['Baixa', 'Normal', 'Alta'];
  const alimentacoes = ['Comeu normalmente', 'Comeu menos que o normal', 'Comeu mais que o normal', 'Não comeu', 'Não observado'];
  const caixas = ['Normal', 'Diferente do habitual', 'Não usou', 'Não observado'];
  const formulario = document.querySelector('#formulario-diario');
  const data = document.querySelector('#data-registro');
  const categoria = document.querySelector('#categoria-registro');
  const humor = document.querySelector('#humor-registro');
  const energia = document.querySelector('#energia-registro');
  const alimentacao = document.querySelector('#alimentacao-registro');
  const caixaAreia = document.querySelector('#caixa-registro');
  const observacao = document.querySelector('#observacao-registro');
  const botaoPrincipal = document.querySelector('#botao-diario');
  const cancelarEdicao = document.querySelector('#cancelar-edicao-diario');
  const adicionarRegistro = document.querySelector('#adicionar-registro');
  const mensagem = document.querySelector('#mensagem-diario');
  const filtroCategoria = document.querySelector('#filtro-categoria-diario');
  const pesquisa = document.querySelector('#pesquisa-diario');
  const limparFiltros = document.querySelector('#limpar-filtros-diario');
  const estadoVazio = document.querySelector('#estado-vazio-diario');
  const lista = document.querySelector('#lista-registros-diario');
  const erros = { data: document.querySelector('#erro-data-registro'), categoria: document.querySelector('#erro-categoria-registro'), humor: document.querySelector('#erro-humor-registro'), energia: document.querySelector('#erro-energia-registro'), alimentacao: document.querySelector('#erro-alimentacao-registro'), caixaAreia: document.querySelector('#erro-caixa-registro'), observacao: document.querySelector('#erro-observacao-registro') };
  let registros = [];
  let registroEmEdicao = null;

  function dataHojeLocal() { const agora = new Date(); const ano = agora.getFullYear(); const mes = String(agora.getMonth() + 1).padStart(2, '0'); const dia = String(agora.getDate()).padStart(2, '0'); return `${ano}-${mes}-${dia}`; }
  function dataCivilValida(valor) { return /^\d{4}-\d{2}-\d{2}$/.test(valor) && !Number.isNaN(Date.UTC(Number(valor.slice(0, 4)), Number(valor.slice(5, 7)) - 1, Number(valor.slice(8, 10))) ) && new Date(Number(valor.slice(0, 4)), Number(valor.slice(5, 7)) - 1, Number(valor.slice(8, 10))).toISOString().slice(0, 10) === valor; }
  function dataParaNumero(valor) { const [ano, mes, dia] = valor.split('-').map(Number); return ano * 10000 + mes * 100 + dia; }
  function formatarData(valor) { const [ano, mes, dia] = valor.split('-').map(Number); return new Intl.DateTimeFormat('pt-BR', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(Date.UTC(ano, mes - 1, dia))); }
  function novoId() { if (globalThis.crypto && typeof globalThis.crypto.randomUUID === 'function') return globalThis.crypto.randomUUID(); return `diario-${Date.now()}-${Math.random().toString(36).slice(2)}`; }
  function registroValido(item) { return item && typeof item === 'object' && typeof item.id === 'string' && item.id && dataCivilValida(item.data) && categorias.includes(item.categoria) && humores.includes(item.humor) && energias.includes(item.energia) && alimentacoes.includes(item.alimentacao) && caixas.includes(item.caixaAreia) && typeof item.observacao === 'string' && item.observacao.length <= LIMITE_OBSERVACAO; }
  function salvarRegistros() { try { localStorage.setItem(CHAVE_DIARIO, JSON.stringify(registros)); return true; } catch (erro) { mensagem.textContent = 'Não foi possível salvar o diário neste navegador.'; return false; } }
  function carregarRegistros() { try { const salvo = localStorage.getItem(CHAVE_DIARIO); if (!salvo) return; const dados = JSON.parse(salvo); if (!Array.isArray(dados)) { localStorage.removeItem(CHAVE_DIARIO); mensagem.textContent = 'Os dados do diário estavam inválidos e foram removidos.'; return; } const ids = new Set(); const validos = dados.filter((item) => registroValido(item) && !ids.has(item.id) && (ids.add(item.id), true)); registros = validos; if (validos.length !== dados.length) { salvarRegistros(); mensagem.textContent = 'Alguns registros inválidos ou duplicados foram descartados.'; } } catch (erro) { try { localStorage.removeItem(CHAVE_DIARIO); } catch (erroAoLimpar) {} mensagem.textContent = 'Os dados do diário estavam corrompidos e foram removidos.'; } }
  function limparErros() { Object.values(erros).forEach((item) => { item.textContent = ''; }); [data, categoria, humor, energia, alimentacao, caixaAreia, observacao].forEach((item) => item.removeAttribute('aria-invalid')); }
  function validarFormulario() { limparErros(); const campos = [[data, 'data', 'Informe a data do registro.'], [categoria, 'categoria', 'Selecione uma categoria.'], [humor, 'humor', 'Selecione o humor do gato.'], [energia, 'energia', 'Selecione o nível de energia.'], [alimentacao, 'alimentacao', 'Selecione como foi a alimentação.'], [caixaAreia, 'caixaAreia', 'Selecione como foi o uso da caixa de areia.']]; const invalidos = []; campos.forEach(([campo, chave, texto]) => { if (!campo.value || (chave === 'data' && !dataCivilValida(campo.value))) { erros[chave].textContent = texto; campo.setAttribute('aria-invalid', 'true'); invalidos.push(campo); } }); if (data.value && dataCivilValida(data.value) && dataParaNumero(data.value) > dataParaNumero(dataHojeLocal())) { erros.data.textContent = 'A data do registro não pode estar no futuro.'; data.setAttribute('aria-invalid', 'true'); invalidos.push(data); } return invalidos; }
  function dadosDoFormulario() { return { id: registroEmEdicao || novoId(), data: data.value, categoria: categoria.value, humor: humor.value, energia: energia.value, alimentacao: alimentacao.value, caixaAreia: caixaAreia.value, observacao: observacao.value.trim() }; }
  function preencherFormulario(registro) { data.value = registro.data; categoria.value = registro.categoria; humor.value = registro.humor; energia.value = registro.energia; alimentacao.value = registro.alimentacao; caixaAreia.value = registro.caixaAreia; observacao.value = registro.observacao; }
  function limparFormulario() { formulario.reset(); data.value = dataHojeLocal(); limparErros(); }
  function mostrarFormulario(novo = true) { formulario.hidden = false; if (novo) { registroEmEdicao = null; limparFormulario(); botaoPrincipal.textContent = 'Salvar registro'; cancelarEdicao.hidden = true; } else { botaoPrincipal.textContent = 'Salvar alterações'; cancelarEdicao.hidden = false; } data.focus(); }
  function esconderFormulario() { formulario.hidden = true; }
  function registroFocado(id) { const alvo = document.querySelector(`[data-registro-id="${id}"]`); if (alvo) alvo.focus(); }
  function registrosFiltrados() { const termo = pesquisa.value.trim().normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('pt-BR'); return registros.map((item, indice) => ({ item, indice })).filter(({ item }) => (filtroCategoria.value === 'todas' || item.categoria === filtroCategoria.value) && (!termo || item.observacao.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('pt-BR').includes(termo))).sort((a, b) => dataParaNumero(b.item.data) - dataParaNumero(a.item.data) || a.indice - b.indice).map(({ item }) => item); }
  function criarRegistro(item) { const li = document.createElement('li'); const article = document.createElement('article'); const titulo = document.createElement('h2'); const dados = document.createElement('dl'); const observacaoTitulo = document.createElement('dt'); const observacaoTexto = document.createElement('dd'); const acoes = document.createElement('div'); const editar = document.createElement('button'); const apagar = document.createElement('button'); article.className = 'registro-diario'; article.tabIndex = -1; article.dataset.registroId = item.id; titulo.textContent = formatarData(item.data); const campos = [['Categoria', item.categoria], ['Humor', item.humor], ['Energia', item.energia], ['Alimentação', item.alimentacao], ['Caixa de areia', item.caixaAreia]]; campos.forEach(([rotulo, valor]) => { const dt = document.createElement('dt'); const dd = document.createElement('dd'); dt.textContent = rotulo; dd.textContent = valor; dados.append(dt, dd); }); observacaoTitulo.textContent = 'Observação'; observacaoTexto.textContent = item.observacao || 'Nenhuma observação registrada.'; dados.append(observacaoTitulo, observacaoTexto); acoes.className = 'acoes-registro-diario'; editar.className = 'botao-tarefa'; editar.type = 'button'; editar.textContent = 'Editar'; editar.setAttribute('aria-label', `Editar registro de ${formatarData(item.data)}`); editar.addEventListener('click', () => iniciarEdicao(item)); apagar.className = 'botao-tarefa'; apagar.type = 'button'; apagar.textContent = 'Apagar'; apagar.setAttribute('aria-label', `Apagar registro de ${formatarData(item.data)}`); apagar.addEventListener('click', () => apagarRegistro(item)); acoes.append(editar, apagar); article.append(titulo, dados, acoes); li.append(article); return li; }
  function renderizar(idParaFocar = null) { const visiveis = registrosFiltrados(); lista.replaceChildren(...visiveis.map(criarRegistro)); estadoVazio.textContent = visiveis.length ? '' : (registros.length ? 'Nenhum registro corresponde aos filtros selecionados.' : 'Ainda não há registros no diário.'); if (idParaFocar) registroFocado(idParaFocar); }
  function iniciarEdicao(item) { registroEmEdicao = item.id; preencherFormulario(item); mostrarFormulario(false); }
  function cancelar() { const id = registroEmEdicao; registroEmEdicao = null; esconderFormulario(); renderizar(id); mensagem.textContent = 'Edição cancelada.'; }
  function apagarRegistro(item) { if (!window.confirm(`Apagar o registro de ${formatarData(item.data)}?`)) return; registros = registros.filter((registro) => registro.id !== item.id); if (!salvarRegistros()) return; renderizar(); mensagem.textContent = 'Registro apagado.'; adicionarRegistro.focus(); }
  adicionarRegistro.addEventListener('click', () => mostrarFormulario()); cancelarEdicao.addEventListener('click', cancelar);
  formulario.addEventListener('submit', (evento) => { evento.preventDefault(); const invalidos = validarFormulario(); if (invalidos.length) { mensagem.textContent = 'Revise os campos do registro.'; invalidos[0].focus(); return; } const registro = dadosDoFormulario(); const id = registro.id; if (registroEmEdicao) registros = registros.map((item) => item.id === registroEmEdicao ? registro : item); else registros.push(registro); if (!salvarRegistros()) return; registroEmEdicao = null; esconderFormulario(); renderizar(id); mensagem.textContent = 'Registro salvo.'; });
  [filtroCategoria, pesquisa].forEach((controle) => controle.addEventListener('input', () => renderizar())); limparFiltros.addEventListener('click', () => { filtroCategoria.value = 'todas'; pesquisa.value = ''; renderizar(); mensagem.textContent = 'Filtros limpos.'; });
  carregarRegistros(); esconderFormulario(); renderizar();
})();
