(() => {
  const CHAVE_GATOS = 'paisDeGatos.cats';
  const CHAVE_ATIVO = 'paisDeGatos.activeCat';
  const formulario = document.querySelector('#formulario-perfil');
  const submit = formulario.querySelector('[type="submit"]');
  const cancelar = document.querySelector('#botao-cancelar');
  const mensagem = document.querySelector('#mensagem-formulario');
  const lista = document.querySelector('#lista-gatos');
  const vazio = document.querySelector('#estado-sem-gatos');
  const textoAtivo = document.querySelector('#gato-ativo');
  const adicionar = document.querySelector('#adicionar-gato');
  const adicionarOutro = document.querySelector('#adicionar-outro-gato');
  const campos = { nome: document.querySelector('#nome-gato'), idade: document.querySelector('#idade-gato'), temperamento: document.querySelector('#temperamento-gato'), atividade: document.querySelector('#atividade-gato'), apelido: document.querySelector('#apelido-gato') };
  const erros = { nome: document.querySelector('#erro-nome-gato'), idade: document.querySelector('#erro-idade-gato'), temperamento: document.querySelector('#erro-temperamento-gato'), atividade: document.querySelector('#erro-atividade-gato'), apelido: document.querySelector('#erro-apelido-gato') };
  let gatos = [];
  let ativo = null;
  let editando = null;
  function idNovo() { return globalThis.crypto?.randomUUID?.() || `cat-${Date.now()}-${Math.random().toString(36).slice(2)}`; }
  function ler() { try { const dados = JSON.parse(localStorage.getItem(CHAVE_GATOS) || '[]'); gatos = Array.isArray(dados) ? dados.filter((g) => g && typeof g.id === 'string' && typeof g.nome === 'string') : []; const salvo = localStorage.getItem(CHAVE_ATIVO); ativo = gatos.some((g) => g.id === salvo) ? salvo : (gatos[0]?.id || null); } catch (erro) { gatos = []; ativo = null; } }
  function salvar() { try { localStorage.setItem(CHAVE_GATOS, JSON.stringify(gatos)); if (ativo) localStorage.setItem(CHAVE_ATIVO, ativo); else localStorage.removeItem(CHAVE_ATIVO); return true; } catch (erro) { return false; } }
  function limparErros() { Object.values(erros).forEach((e) => { e.textContent = ''; }); Object.values(campos).forEach((c) => c.removeAttribute('aria-invalid')); }
  function validar() { const resultado = {}; const nome = campos.nome.value.trim(); const idade = campos.idade.value.trim(); if (nome.length < 2) resultado.nome = 'Informe o nome do gato com pelo menos 2 caracteres.'; if (!idade || !Number.isInteger(Number(idade)) || Number(idade) < 0 || Number(idade) > 40) resultado.idade = 'Informe uma idade inteira entre 0 e 40 anos.'; if (!campos.temperamento.value) resultado.temperamento = 'Selecione o temperamento do gato.'; if (!campos.atividade.value) resultado.atividade = 'Selecione a atividade favorita do gato.'; if (campos.apelido.value.trim().length > 40) resultado.apelido = 'O apelido deve ter no máximo 40 caracteres.'; return resultado; }
  function dadosFormulario() { return { id: editando || idNovo(), nome: campos.nome.value.trim(), idade: Number(campos.idade.value), temperamento: campos.temperamento.value, atividade: campos.atividade.value, apelido: campos.apelido.value.trim() }; }
  function preencher(g) { campos.nome.value = g.nome; campos.idade.value = g.idade; campos.temperamento.value = g.temperamento; campos.atividade.value = g.atividade; campos.apelido.value = g.apelido || ''; }
  function abrirFormulario(gato = null) { editando = gato?.id || null; formulario.hidden = false; lista.hidden = true; vazio.hidden = true; adicionarOutro.hidden = true; submit.textContent = gato ? 'Salvar alterações' : 'Criar gato'; cancelar.hidden = !gato; if (gato) preencher(gato); else formulario.reset(); limparErros(); campos.nome.focus(); }
  function selecionar(id) { ativo = id; salvar(); renderizar(); mensagem.textContent = 'Gato ativo atualizado.'; document.querySelector(`[data-cat-id="${id}"] .botao-selecionar`)?.focus(); }
  function apagar(gato) { if (!window.confirm(`Apagar ${gato.nome}? As tarefas e registros desse gato também deixarão de aparecer.`)) return; gatos = gatos.filter((g) => g.id !== gato.id); if (ativo === gato.id) ativo = gatos[0]?.id || null; if (!salvar()) { mensagem.textContent = 'Não foi possível apagar o gato.'; return; } mensagem.textContent = 'Gato apagado.'; renderizar(); }
  function card(gato) { const article = document.createElement('article'); article.className = 'ficha-gato'; article.dataset.catId = gato.id; const titulo = document.createElement('h2'); titulo.textContent = gato.apelido ? `${gato.nome} (${gato.apelido})` : gato.nome; const dados = document.createElement('p'); dados.textContent = `${gato.idade} ${gato.idade === 1 ? 'ano' : 'anos'} · ${gato.temperamento} · ${gato.atividade}`; const estado = document.createElement('p'); estado.textContent = gato.id === ativo ? 'Gato ativo' : 'Gato não selecionado'; const acoes = document.createElement('div'); const selecionarBotao = document.createElement('button'); selecionarBotao.className = 'botao botao-selecionar'; selecionarBotao.type = 'button'; selecionarBotao.textContent = gato.id === ativo ? 'Gato selecionado' : `Selecionar ${gato.nome}`; selecionarBotao.disabled = gato.id === ativo; selecionarBotao.addEventListener('click', () => selecionar(gato.id)); const editar = document.createElement('button'); editar.className = 'botao'; editar.type = 'button'; editar.textContent = 'Editar'; editar.setAttribute('aria-label', `Editar ${gato.nome}`); editar.addEventListener('click', () => abrirFormulario(gato)); const apagarBotao = document.createElement('button'); apagarBotao.className = 'botao-apagar'; apagarBotao.type = 'button'; apagarBotao.textContent = 'Apagar'; apagarBotao.setAttribute('aria-label', `Apagar ${gato.nome}`); apagarBotao.addEventListener('click', () => apagar(gato)); acoes.append(selecionarBotao, editar, apagarBotao); article.append(titulo, dados, estado, acoes); return article; }
  function renderizar() { const tem = gatos.length > 0; vazio.hidden = tem; lista.hidden = !tem; adicionar.hidden = tem; adicionarOutro.hidden = !tem; lista.replaceChildren(...gatos.map(card)); const gato = gatos.find((g) => g.id === ativo); textoAtivo.textContent = gato ? `Gato ativo: ${gato.nome}.` : ''; }
  formulario.addEventListener('submit', (evento) => { evento.preventDefault(); limparErros(); const falhas = validar(); if (Object.keys(falhas).length) { Object.entries(falhas).forEach(([chave, texto]) => { erros[chave].textContent = texto; campos[chave].setAttribute('aria-invalid', 'true'); }); mensagem.textContent = 'Revise os campos indicados.'; campos[Object.keys(falhas)[0]].focus(); return; } const gato = dadosFormulario(); if (editando) gatos = gatos.map((item) => item.id === editando ? gato : item); else { gatos.push(gato); ativo = gato.id; } if (!salvar()) { mensagem.textContent = 'Não foi possível salvar o gato.'; return; } formulario.hidden = true; editando = null; mensagem.textContent = 'Gato salvo com sucesso.'; renderizar(); document.querySelector(`[data-cat-id="${gato.id}"] .botao-selecionar`)?.focus(); });
  cancelar.addEventListener('click', () => { editando = null; formulario.hidden = true; renderizar(); mensagem.textContent = 'Edição cancelada.'; });
  adicionar.addEventListener('click', () => abrirFormulario()); adicionarOutro.addEventListener('click', () => abrirFormulario());
  ler(); renderizar();
})();
